//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class a_AntibioticNorms
    {
        public int id { get; set; }
        public int idCulture { get; set; }
        public Nullable<int> valuePermissiblemMin { get; set; }
        public Nullable<int> valuePermissiblemMax { get; set; }
        public Nullable<int> valueTargetMin { get; set; }
        public Nullable<int> valueTargetMax { get; set; }
        public Nullable<int> index { get; set; }
        public Nullable<int> idConsumable { get; set; }
    
        public virtual d_Consumables d_Consumables { get; set; }
        public virtual d_Microorganism d_Microorganism { get; set; }
    }
}
