//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class a_AntibioticPanel
    {
        public int id { get; set; }
        public Nullable<int> idAntibioticPanelName { get; set; }
        public Nullable<bool> fistLine { get; set; }
        public Nullable<int> index { get; set; }
        public Nullable<bool> show { get; set; }
        public Nullable<int> id_ABMOGroup { get; set; }
    
        public virtual a_AntibioticPanelName a_AntibioticPanelName { get; set; }
        public virtual a_AntibioticMicroorganismGroup a_AntibioticMicroorganismGroup { get; set; }
    }
}
