//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class a_AntibioticMicroorganismGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public a_AntibioticMicroorganismGroup()
        {
            this.a_AntibioticPanel = new HashSet<a_AntibioticPanel>();
            this.g_ABDisk_ABTest_Interpritation = new HashSet<g_ABDisk_ABTest_Interpritation>();
        }
    
        public int id { get; set; }
        public Nullable<int> idGroupMO { get; set; }
        public Nullable<int> sen { get; set; }
        public Nullable<int> res { get; set; }
        public Nullable<int> index { get; set; }
        public Nullable<bool> show { get; set; }
        public string comments { get; set; }
        public string specificity { get; set; }
        public string interpretation { get; set; }
        public Nullable<int> idConsumable { get; set; }
        public Nullable<bool> forScrining { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<a_AntibioticPanel> a_AntibioticPanel { get; set; }
        public virtual d_MicroorganismGroup d_MicroorganismGroup { get; set; }
        public virtual d_Consumables d_Consumables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<g_ABDisk_ABTest_Interpritation> g_ABDisk_ABTest_Interpritation { get; set; }
    }
}
