//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class a_AntibioticPanelName
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public a_AntibioticPanelName()
        {
            this.a_AntibioticPanel = new HashSet<a_AntibioticPanel>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> idGroupMO { get; set; }
        public string specificity { get; set; }
        public Nullable<int> index { get; set; }
        public Nullable<bool> show { get; set; }
        public int idSubdivisions { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<a_AntibioticPanel> a_AntibioticPanel { get; set; }
        public virtual d_MicroorganismGroup d_MicroorganismGroup { get; set; }
        public virtual d_Subdivisions d_Subdivisions { get; set; }
    }
}
