//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class Analysis
    {
        public long id { get; set; }
        public int num { get; set; }
        public int finance { get; set; }
        public Nullable<System.DateTime> dateSampling { get; set; }
        public Nullable<System.DateTime> dateAvailable { get; set; }
        public long id_patient { get; set; }
        public Nullable<int> idInstitution { get; set; }
        public Nullable<int> idDepartment { get; set; }
        public string numMedCards { get; set; }
        public Nullable<int> idMaterial { get; set; }
        public Nullable<int> idGroupOfStudy { get; set; }
        public Nullable<int> idDiagnosis { get; set; }
        public Nullable<int> idPurposeofStudy { get; set; }
        public Nullable<int> idCategoryOfPatient { get; set; }
        public string sentDoctor { get; set; }
        public Nullable<int> idBritrany { get; set; }
    
        public virtual d_Finance d_Finance { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Britrany Britrany { get; set; }
        public virtual d_Category_of_patient d_Category_of_patient { get; set; }
        public virtual d_Department d_Department { get; set; }
        public virtual d_Diagnosis d_Diagnosis { get; set; }
        public virtual d_Group_of_Study d_Group_of_Study { get; set; }
        public virtual d_Institution d_Institution { get; set; }
        public virtual d_Material d_Material { get; set; }
        public virtual d_Purpose_of_study d_Purpose_of_study { get; set; }
    }
}
