//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_Analyzes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public d_Analyzes()
        {
            this.p_Analises_DB = new HashSet<p_Analises_DB>();
            this.p_Analises_Mediums = new HashSet<p_Analises_Mediums>();
            this.p_Analises_Cultures = new HashSet<p_Analises_Cultures>();
        }
    
        public int id { get; set; }
        public int labNum { get; set; }
        public Nullable<System.DateTime> dateSampling { get; set; }
        public Nullable<System.DateTime> dateDelivery { get; set; }
        public Nullable<int> idPatient { get; set; }
        public string numMedCard { get; set; }
        public Nullable<int> idGMP { get; set; }
        public Nullable<System.DateTime> dateEnd { get; set; }
        public byte[] rezult { get; set; }
        public Nullable<int> idFinance { get; set; }
        public Nullable<int> idInstitution { get; set; }
        public Nullable<int> idDepartment { get; set; }
        public Nullable<int> idPatientStatus { get; set; }
        public Nullable<int> idSentPerson { get; set; }
        public Nullable<int> idResTemplate { get; set; }
        public Nullable<int> idDoctor { get; set; }
        public Nullable<int> agePatient { get; set; }
        public string comment { get; set; }
        public Nullable<int> idInstitutionLaboratorii { get; set; }
        public Nullable<bool> do48 { get; set; }
        public Nullable<bool> do72 { get; set; }
        public Nullable<int> idAB1 { get; set; }
        public Nullable<int> idAB2 { get; set; }
        public Nullable<int> idAB3 { get; set; }
        public Nullable<int> idAB4 { get; set; }
        public Nullable<System.DateTime> timeSampling { get; set; }
        public Nullable<System.DateTime> timeDelivery { get; set; }
        public Nullable<System.DateTime> timeEnd { get; set; }
        public Nullable<bool> isFirstGospitelisation { get; set; }
        public Nullable<bool> wasPreviousBac { get; set; }
        public int idSubdivisions { get; set; }
        public Nullable<int> idStaffRegistration { get; set; }
        public Nullable<int> idBrakerage { get; set; }
        public string cvc { get; set; }
        public string uc { get; set; }
        public string pc { get; set; }
        public string ssi { get; set; }
        public string uti { get; set; }
        public string vap { get; set; }
        public string bacteriemia { get; set; }
        public Nullable<int> idJobPlace { get; set; }
        public Nullable<int> idJob { get; set; }
        public Nullable<int> idWhoPay { get; set; }
        public Nullable<bool> isPay { get; set; }
        public Nullable<int> idJobPlaceGroup { get; set; }
        public Nullable<int> idJobStatus { get; set; }
        public Nullable<int> idStaffVydano { get; set; }
        public Nullable<int> idTerra { get; set; }
        public Nullable<int> idTerraGMP { get; set; }
        public Nullable<bool> inRaxunok { get; set; }
        public Nullable<bool> isEnd { get; set; }
        public Nullable<bool> isSend { get; set; }
        public Nullable<bool> isPrint { get; set; }
        public Nullable<bool> isVydano { get; set; }
        public Nullable<System.DateTime> dateVydano { get; set; }
        public Nullable<bool> isSendToTerra { get; set; }
        public string rezultPath { get; set; }
        public string diagnosis { get; set; }
        public Nullable<int> idDiagnosisGroup { get; set; }
    
        public virtual d_Staff d_Staff { get; set; }
        public virtual d_Department d_Department { get; set; }
        public virtual d_Finance d_Finance { get; set; }
        public virtual p_Group_Material_Purpose p_Group_Material_Purpose { get; set; }
        public virtual d_Institution d_Institution { get; set; }
        public virtual d_PatientStatus d_PatientStatus { get; set; }
        public virtual d_Patients d_Patients { get; set; }
        public virtual d_ResTemplate d_ResTemplate { get; set; }
        public virtual d_SentPerson d_SentPerson { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<p_Analises_DB> p_Analises_DB { get; set; }
        public virtual d_TestAndAntibiotic d_TestAndAntibiotic { get; set; }
        public virtual d_TestAndAntibiotic d_TestAndAntibiotic1 { get; set; }
        public virtual d_TestAndAntibiotic d_TestAndAntibiotic2 { get; set; }
        public virtual d_TestAndAntibiotic d_TestAndAntibiotic3 { get; set; }
        public virtual d_Brakerage d_Brakerage { get; set; }
        public virtual d_DiagnosisGroup d_DiagnosisGroup { get; set; }
        public virtual d_Institution d_Institution1 { get; set; }
        public virtual d_Job d_Job { get; set; }
        public virtual d_JobPlace d_JobPlace { get; set; }
        public virtual d_JobPlaceGroup d_JobPlaceGroup { get; set; }
        public virtual d_JobStatus d_JobStatus { get; set; }
        public virtual d_Staff d_Staff1 { get; set; }
        public virtual d_Staff d_Staff2 { get; set; }
        public virtual d_Subdivisions d_Subdivisions { get; set; }
        public virtual d_WhoPay d_WhoPay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<p_Analises_Mediums> p_Analises_Mediums { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<p_Analises_Cultures> p_Analises_Cultures { get; set; }
    }
}
