//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_Biovariant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public d_Biovariant()
        {
            this.p_Analises_Cultures = new HashSet<p_Analises_Cultures>();
            this.p_Analises_Mediums_Date_Colonies = new HashSet<p_Analises_Mediums_Date_Colonies>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> idMicroorganism { get; set; }
        public Nullable<int> idSerotype { get; set; }
        public Nullable<int> index { get; set; }
        public Nullable<bool> show { get; set; }
        public Nullable<int> idMicroorganismGroup { get; set; }
    
        public virtual d_Microorganism d_Microorganism { get; set; }
        public virtual d_Serotype d_Serotype { get; set; }
        public virtual d_MicroorganismGroup d_MicroorganismGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<p_Analises_Cultures> p_Analises_Cultures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<p_Analises_Mediums_Date_Colonies> p_Analises_Mediums_Date_Colonies { get; set; }
    }
}
