//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_ConsumablesOrder
    {
        public int id { get; set; }
        public Nullable<int> idConsumable { get; set; }
        public Nullable<double> avarage { get; set; }
        public Nullable<int> idPeriod { get; set; }
        public Nullable<bool> inOrder { get; set; }
        public Nullable<int> idUnit { get; set; }
        public Nullable<int> idSubdivision { get; set; }
    
        public virtual d_Consumables d_Consumables { get; set; }
        public virtual d_Period d_Period { get; set; }
        public virtual d_Subdivisions d_Subdivisions { get; set; }
        public virtual d_Units d_Units { get; set; }
    }
}
