//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_ConsumablesControls
    {
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public int idConsumableStock { get; set; }
        public int idCulture { get; set; }
        public Nullable<int> valuePermissiblemMin { get; set; }
        public Nullable<int> valuePermissiblemMax { get; set; }
        public Nullable<int> valueTargetMin { get; set; }
        public Nullable<int> valueTargetMax { get; set; }
        public Nullable<int> valueCurrent { get; set; }
        public Nullable<int> idStaff { get; set; }
        public int idSubdivisions { get; set; }
        public Nullable<bool> isEnterControl { get; set; }
        public string descriptionControl { get; set; }
        public string valueControl { get; set; }
        public string comment { get; set; }
        public Nullable<int> idConsumableGroup { get; set; }
        public string rightControl { get; set; }
    
        public virtual d_ConsumablesGroup d_ConsumablesGroup { get; set; }
        public virtual d_ConsumablesStock d_ConsumablesStock { get; set; }
        public virtual d_Microorganism d_Microorganism { get; set; }
        public virtual d_Staff d_Staff { get; set; }
        public virtual d_Subdivisions d_Subdivisions { get; set; }
    }
}
