//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_ConsumablesStock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public d_ConsumablesStock()
        {
            this.a_AntibioticControl = new HashSet<a_AntibioticControl>();
            this.d_ConsumableWritingOff = new HashSet<d_ConsumableWritingOff>();
            this.p_Analises_Mediums_Date_Colonies_AB = new HashSet<p_Analises_Mediums_Date_Colonies_AB>();
        }
    
        public int id { get; set; }
        public string series { get; set; }
        public Nullable<System.DateTime> termin { get; set; }
        public Nullable<bool> show { get; set; }
        public string conclusion { get; set; }
        public Nullable<System.DateTime> dateDelivery { get; set; }
        public Nullable<int> idProducer { get; set; }
        public int idSubdivisions { get; set; }
        public Nullable<int> idFinance { get; set; }
        public Nullable<double> quantityWas { get; set; }
        public Nullable<double> quantityBecame { get; set; }
        public Nullable<int> idUnits { get; set; }
        public string comment { get; set; }
        public Nullable<bool> isEnd { get; set; }
        public Nullable<System.DateTime> dateEnd { get; set; }
        public Nullable<int> idConsumablesGroup { get; set; }
        public Nullable<int> idConsumable { get; set; }
        public Nullable<bool> isTerminEnd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<a_AntibioticControl> a_AntibioticControl { get; set; }
        public virtual d_Consumables d_Consumables { get; set; }
        public virtual d_ConsumablesGroup d_ConsumablesGroup { get; set; }
        public virtual d_Finance d_Finance { get; set; }
        public virtual d_Producer d_Producer { get; set; }
        public virtual d_Subdivisions d_Subdivisions { get; set; }
        public virtual d_Units d_Units { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<d_ConsumableWritingOff> d_ConsumableWritingOff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<p_Analises_Mediums_Date_Colonies_AB> p_Analises_Mediums_Date_Colonies_AB { get; set; }
    }
}
