//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_ConsumableWritingOff
    {
        public int id { get; set; }
        public int idConsumablesStock { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<double> quantity { get; set; }
        public Nullable<bool> isPlus { get; set; }
        public Nullable<int> idUnits { get; set; }
        public Nullable<double> quantityWas { get; set; }
        public Nullable<double> quantityBecame { get; set; }
        public Nullable<int> idStaff { get; set; }
    
        public virtual d_Staff d_Staff { get; set; }
        public virtual d_Units d_Units { get; set; }
        public virtual d_ConsumablesStock d_ConsumablesStock { get; set; }
    }
}
