//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_Consumables
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public d_Consumables()
        {
            this.d_TestAndAntibiotic1 = new HashSet<d_TestAndAntibiotic>();
            this.g_ABDisk_ABTest_Interpritation = new HashSet<g_ABDisk_ABTest_Interpritation>();
            this.p_Analises_Cultures_ABDisk = new HashSet<p_Analises_Cultures_ABDisk>();
            this.p_Analises_Mediums_Date_Colonies_AB = new HashSet<p_Analises_Mediums_Date_Colonies_AB>();
            this.a_AntibioticMicroorganismGroup = new HashSet<a_AntibioticMicroorganismGroup>();
            this.d_ConsumablesStock = new HashSet<d_ConsumablesStock>();
            this.d_ConsumablesOrder = new HashSet<d_ConsumablesOrder>();
            this.d_ConsumablesNorms = new HashSet<d_ConsumablesNorms>();
            this.g_Medium_Consumables = new HashSet<g_Medium_Consumables>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string abbr { get; set; }
        public Nullable<int> index { get; set; }
        public Nullable<bool> show { get; set; }
        public Nullable<int> idAB { get; set; }
        public Nullable<int> idConsumablesGroup { get; set; }
    
        public virtual d_ConsumablesGroup d_ConsumablesGroup { get; set; }
        public virtual d_TestAndAntibiotic d_TestAndAntibiotic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<d_TestAndAntibiotic> d_TestAndAntibiotic1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<g_ABDisk_ABTest_Interpritation> g_ABDisk_ABTest_Interpritation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<p_Analises_Cultures_ABDisk> p_Analises_Cultures_ABDisk { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<p_Analises_Mediums_Date_Colonies_AB> p_Analises_Mediums_Date_Colonies_AB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<a_AntibioticMicroorganismGroup> a_AntibioticMicroorganismGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<d_ConsumablesStock> d_ConsumablesStock { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<d_ConsumablesOrder> d_ConsumablesOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<d_ConsumablesNorms> d_ConsumablesNorms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<g_Medium_Consumables> g_Medium_Consumables { get; set; }
    }
}
