//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_Equipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public d_Equipment()
        {
            this.d_Equipment1 = new HashSet<d_Equipment>();
            this.g_Equipment_DragMatal = new HashSet<g_Equipment_DragMatal>();
            this.p_Inner_Control = new HashSet<p_Inner_Control>();
            this.p_Inner_Control1 = new HashSet<p_Inner_Control>();
        }
    
        public int id { get; set; }
        public bool isMain { get; set; }
        public Nullable<int> idEquipmentGroup { get; set; }
        public string name { get; set; }
        public string model { get; set; }
        public string labNum { get; set; }
        public string zavNum { get; set; }
        public string invNum { get; set; }
        public Nullable<bool> isPassport { get; set; }
        public string manufacturer { get; set; }
        public string comment { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<bool> isAccreditation { get; set; }
        public string currentMode { get; set; }
        public string passportMode { get; set; }
        public Nullable<int> idThermometer { get; set; }
        public Nullable<int> index { get; set; }
        public string atestation { get; set; }
        public Nullable<int> yearManufacturer { get; set; }
        public Nullable<int> yearІnstallation { get; set; }
        public Nullable<int> idRoom { get; set; }
        public Nullable<int> idDisinfectants { get; set; }
        public Nullable<int> power { get; set; }
        public Nullable<int> resource { get; set; }
        public Nullable<double> bactericidal_flow { get; set; }
        public Nullable<double> coefficient { get; set; }
        public Nullable<int> time_Disinfectants { get; set; }
        public Nullable<int> idEquipmentState { get; set; }
        public string time_workUFO { get; set; }
        public int idSubdivisions { get; set; }
        public string dateCalibration { get; set; }
        public string dateCalibrationNext { get; set; }
        public string technicalCharacteristics { get; set; }
        public string workMode { get; set; }
    
        public virtual d_Disinfectants d_Disinfectants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<d_Equipment> d_Equipment1 { get; set; }
        public virtual d_Equipment d_Equipment2 { get; set; }
        public virtual d_EquipmentGroup d_EquipmentGroup { get; set; }
        public virtual d_EquipmentState d_EquipmentState { get; set; }
        public virtual d_Room d_Room { get; set; }
        public virtual d_Subdivisions d_Subdivisions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<g_Equipment_DragMatal> g_Equipment_DragMatal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<p_Inner_Control> p_Inner_Control { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<p_Inner_Control> p_Inner_Control1 { get; set; }
    }
}
