//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_Laboratoria
    {
        public int id { get; set; }
        public int idSubdivisions { get; set; }
        public string nameLab { get; set; }
        public string abbrLab { get; set; }
        public string email { get; set; }
        public string parol { get; set; }
        public Nullable<bool> A5 { get; set; }
        public string telephon { get; set; }
        public string institution { get; set; }
        public string name { get; set; }
        public string adress { get; set; }
        public string abbrInstitution { get; set; }
        public string chiefName { get; set; }
        public string chiefAbbr { get; set; }
        public string position { get; set; }
    
        public virtual d_Subdivisions d_Subdivisions { get; set; }
    }
}
