//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_Microorganisms
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public d_Microorganisms()
        {
            this.p_AB_MO_group_profile = new HashSet<p_AB_MO_group_profile>();
            this.p_Identification_Table = new HashSet<p_Identification_Table>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_group { get; set; }
        public int id_genus { get; set; }
        public string species { get; set; }
    
        public virtual d_Microorganisms_genus d_Microorganisms_genus { get; set; }
        public virtual d_Microorganisms_groups d_Microorganisms_groups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<p_AB_MO_group_profile> p_AB_MO_group_profile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<p_Identification_Table> p_Identification_Table { get; set; }
    }
}
