//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_Olkenickiy
    {
        public int id { get; set; }
        public Nullable<int> name_test_set { get; set; }
        public string typeOlk { get; set; }
    
        public virtual d_Name_Test_Set d_Name_Test_Set { get; set; }
    }
}
