//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_PriceList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public d_PriceList()
        {
            this.d_Microorganism = new HashSet<d_Microorganism>();
            this.p_Group_Material_Purpose = new HashSet<p_Group_Material_Purpose>();
        }
    
        public int id { get; set; }
        public Nullable<int> index { get; set; }
        public Nullable<bool> show { get; set; }
        public string point { get; set; }
        public string name { get; set; }
        public string abbr { get; set; }
        public Nullable<bool> notCountPos { get; set; }
        public Nullable<double> withoutPDV { get; set; }
        public Nullable<double> withPDV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<d_Microorganism> d_Microorganism { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<p_Group_Material_Purpose> p_Group_Material_Purpose { get; set; }
    }
}
