//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public d_Room()
        {
            this.d_Equipment = new HashSet<d_Equipment>();
            this.p_Inner_Control = new HashSet<p_Inner_Control>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string abbr { get; set; }
        public Nullable<int> index { get; set; }
        public Nullable<bool> show { get; set; }
        public Nullable<double> square { get; set; }
        public Nullable<double> height { get; set; }
        public Nullable<int> timeUFO_1 { get; set; }
        public Nullable<int> timeUFO_2 { get; set; }
        public Nullable<int> timeUFO_3 { get; set; }
        public string cleaning { get; set; }
        public Nullable<int> idStaff { get; set; }
        public Nullable<int> idStaffCleaning { get; set; }
        public string temperature { get; set; }
        public string humidity { get; set; }
        public int idSubdivisions { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<d_Equipment> d_Equipment { get; set; }
        public virtual d_Staff d_Staff { get; set; }
        public virtual d_Staff d_Staff1 { get; set; }
        public virtual d_Subdivisions d_Subdivisions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<p_Inner_Control> p_Inner_Control { get; set; }
    }
}
