//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_SerumStock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public d_SerumStock()
        {
            this.p_Analises_Mediums_Date_Colonies_Serums = new HashSet<p_Analises_Mediums_Date_Colonies_Serums>();
        }
    
        public int id { get; set; }
        public int idSerum { get; set; }
        public string series { get; set; }
        public Nullable<System.DateTime> termin { get; set; }
        public string conclucion { get; set; }
        public Nullable<System.DateTime> dateDelivery { get; set; }
        public Nullable<int> idProducer { get; set; }
        public Nullable<int> idSubdivisions { get; set; }
        public Nullable<bool> show { get; set; }
    
        public virtual d_Producer d_Producer { get; set; }
        public virtual d_Serum d_Serum { get; set; }
        public virtual d_Subdivisions d_Subdivisions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<p_Analises_Mediums_Date_Colonies_Serums> p_Analises_Mediums_Date_Colonies_Serums { get; set; }
    }
}
