//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_Spirt
    {
        public int id { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public Nullable<int> water_xol_analis { get; set; }
        public Nullable<int> water_xol_search { get; set; }
        public Nullable<int> zmyvy_BGKP_analis { get; set; }
        public Nullable<int> zmyvy_BGKP_search { get; set; }
        public Nullable<int> zmyvy_St_analis { get; set; }
        public Nullable<int> zmyvy_St_search { get; set; }
        public Nullable<int> zmyvy_Pat_search { get; set; }
        public Nullable<int> zmyvy_Pat_analis { get; set; }
        public Nullable<int> sterylnist_search { get; set; }
        public Nullable<int> sterylnist_analis { get; set; }
        public Nullable<int> air_analis { get; set; }
        public Nullable<int> air_search { get; set; }
        public Nullable<int> water_analis { get; set; }
        public Nullable<int> water_search { get; set; }
        public Nullable<int> waterRiver_analis { get; set; }
        public Nullable<int> waterRiver_search { get; set; }
        public Nullable<int> water_stichna_analis { get; set; }
        public Nullable<int> water_stichna_search { get; set; }
        public Nullable<int> grunt_analis { get; set; }
        public Nullable<int> grunt_search { get; set; }
        public Nullable<int> des_contam_analis { get; set; }
        public Nullable<int> des_contam_search { get; set; }
        public Nullable<int> liki_analis { get; set; }
        public Nullable<int> liki_search { get; set; }
        public Nullable<int> food_analis { get; set; }
        public Nullable<int> food_search { get; set; }
        public Nullable<int> botulism_analis { get; set; }
        public Nullable<int> botulism_search { get; set; }
        public Nullable<int> mazky { get; set; }
        public Nullable<double> spirtMazky { get; set; }
        public Nullable<double> spirtPrygotuvannyReactyviv { get; set; }
        public Nullable<int> filtrApparat { get; set; }
        public Nullable<double> spirtFiltrAppart { get; set; }
        public Nullable<double> spirtObrobkaHandTable { get; set; }
        public Nullable<double> spirtObrobkaTermostat { get; set; }
        public Nullable<int> zadachi { get; set; }
        public Nullable<double> spirtZadachi { get; set; }
        public Nullable<int> krany { get; set; }
        public Nullable<double> spirtKrany { get; set; }
        public Nullable<double> spirtEntomolog { get; set; }
        public Nullable<int> controly { get; set; }
        public Nullable<double> spirtControly { get; set; }
        public Nullable<int> vsyogoSearch { get; set; }
        public Nullable<double> spirtSearch { get; set; }
        public Nullable<int> vsyogoSBD { get; set; }
        public Nullable<double> spirtSBD { get; set; }
        public Nullable<double> spirtSumOther { get; set; }
        public Nullable<double> spirtVsyogo { get; set; }
        public Nullable<double> spirtOther { get; set; }
        public string commentOther { get; set; }
        public Nullable<double> spirtVnutryshnePeremishenya { get; set; }
        public Nullable<int> idConsumableWritingOff { get; set; }
        public Nullable<int> water_fagy_analis { get; set; }
        public Nullable<int> water_fagy_search { get; set; }
        public Nullable<int> water_paraz_analis { get; set; }
        public Nullable<int> water_paraz_search { get; set; }
        public Nullable<int> waterRiver_paraz_analis { get; set; }
        public Nullable<int> waterRiver_paraz_search { get; set; }
        public Nullable<int> grunt_paraz_analis { get; set; }
        public Nullable<int> grunt_paraz_search { get; set; }
        public Nullable<int> des_chutlyvist_analis { get; set; }
        public Nullable<int> des_chutlyvist_search { get; set; }
        public Nullable<int> watrePool_analis { get; set; }
        public Nullable<int> waterPool_search { get; set; }
        public Nullable<int> controlyAvtoclavov_analis { get; set; }
        public Nullable<int> controlyAvtoclavov_search { get; set; }
        public Nullable<int> waterBeach_analis { get; set; }
        public Nullable<int> waterBeach_search { get; set; }
    
        public virtual d_ConsumableWritingOff d_ConsumableWritingOff { get; set; }
    }
}
