//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_Staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public d_Staff()
        {
            this.a_AntibioticControl = new HashSet<a_AntibioticControl>();
            this.d_Analyzes = new HashSet<d_Analyzes>();
            this.d_Analyzes1 = new HashSet<d_Analyzes>();
            this.d_Analyzes2 = new HashSet<d_Analyzes>();
            this.d_ConsumableWritingOff = new HashSet<d_ConsumableWritingOff>();
            this.d_Room = new HashSet<d_Room>();
            this.d_Room1 = new HashSet<d_Room>();
            this.d_Staff1 = new HashSet<d_Staff>();
            this.l_log = new HashSet<l_log>();
            this.p_Inner_Control = new HashSet<p_Inner_Control>();
            this.s_Orders_Analyzes = new HashSet<s_Orders_Analyzes>();
            this.s_Orders = new HashSet<s_Orders>();
            this.s_Orders1 = new HashSet<s_Orders>();
            this.d_StyleApp = new HashSet<d_StyleApp>();
        }
    
        public int id { get; set; }
        public int id_category { get; set; }
        public string adress { get; set; }
        public string telephon1 { get; set; }
        public string telephon2 { get; set; }
        public string telephon3 { get; set; }
        public string name { get; set; }
        public string abbr { get; set; }
        public Nullable<int> index { get; set; }
        public Nullable<bool> show { get; set; }
        public string parol { get; set; }
        public Nullable<System.DateTime> date_employment { get; set; }
        public Nullable<System.DateTime> date_dismissal { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public Nullable<int> idStaffAlarm { get; set; }
        public int idSubdivisions { get; set; }
        public Nullable<bool> isChief { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<a_AntibioticControl> a_AntibioticControl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<d_Analyzes> d_Analyzes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<d_Analyzes> d_Analyzes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<d_Analyzes> d_Analyzes2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<d_ConsumableWritingOff> d_ConsumableWritingOff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<d_Room> d_Room { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<d_Room> d_Room1 { get; set; }
        public virtual d_StaffGroup d_StaffGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<d_Staff> d_Staff1 { get; set; }
        public virtual d_Staff d_Staff2 { get; set; }
        public virtual d_Subdivisions d_Subdivisions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<l_log> l_log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<p_Inner_Control> p_Inner_Control { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<s_Orders_Analyzes> s_Orders_Analyzes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<s_Orders> s_Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<s_Orders> s_Orders1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<d_StyleApp> d_StyleApp { get; set; }
    }
}
