//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_Subdivisions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public d_Subdivisions()
        {
            this.a_AntibioticControl = new HashSet<a_AntibioticControl>();
            this.a_AntibioticPanelName = new HashSet<a_AntibioticPanelName>();
            this.d_Analyzes = new HashSet<d_Analyzes>();
            this.d_Equipment = new HashSet<d_Equipment>();
            this.d_Laboratoria = new HashSet<d_Laboratoria>();
            this.d_Room = new HashSet<d_Room>();
            this.d_SerumStock = new HashSet<d_SerumStock>();
            this.d_Staff = new HashSet<d_Staff>();
            this.s_Orders_Analyzes = new HashSet<s_Orders_Analyzes>();
            this.s_Orders = new HashSet<s_Orders>();
            this.d_ConsumablesStock = new HashSet<d_ConsumablesStock>();
            this.d_ConsumablesOrder = new HashSet<d_ConsumablesOrder>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string abbr { get; set; }
        public Nullable<bool> show { get; set; }
        public Nullable<int> index { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<a_AntibioticControl> a_AntibioticControl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<a_AntibioticPanelName> a_AntibioticPanelName { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<d_Analyzes> d_Analyzes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<d_Equipment> d_Equipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<d_Laboratoria> d_Laboratoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<d_Room> d_Room { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<d_SerumStock> d_SerumStock { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<d_Staff> d_Staff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<s_Orders_Analyzes> s_Orders_Analyzes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<s_Orders> s_Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<d_ConsumablesStock> d_ConsumablesStock { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<d_ConsumablesOrder> d_ConsumablesOrder { get; set; }
    }
}
