//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_TestsPanel
    {
        public int id { get; set; }
        public int idTestsPanelName { get; set; }
        public Nullable<int> index { get; set; }
        public Nullable<bool> show { get; set; }
        public Nullable<int> idTestAndAntibiotic { get; set; }
    
        public virtual d_TestAndAntibiotic d_TestAndAntibiotic { get; set; }
        public virtual d_TestsPanelName d_TestsPanelName { get; set; }
    }
}
