//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_TestAndAntibiotic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public d_TestAndAntibiotic()
        {
            this.d_Analyzes = new HashSet<d_Analyzes>();
            this.d_Analyzes1 = new HashSet<d_Analyzes>();
            this.d_Analyzes2 = new HashSet<d_Analyzes>();
            this.d_Analyzes3 = new HashSet<d_Analyzes>();
            this.d_Consumables = new HashSet<d_Consumables>();
            this.d_TestsPanel = new HashSet<d_TestsPanel>();
            this.g_ABDisk_ABTest_Interpritation = new HashSet<g_ABDisk_ABTest_Interpritation>();
            this.g_Microorganism_ABResSen = new HashSet<g_Microorganism_ABResSen>();
            this.g_Microorganism_TestsResults = new HashSet<g_Microorganism_TestsResults>();
            this.p_Analises_Cultures_ABTest = new HashSet<p_Analises_Cultures_ABTest>();
            this.p_Analises_Mediums_Date_Colonies_Tests = new HashSet<p_Analises_Mediums_Date_Colonies_Tests>();
        }
    
        public int id { get; set; }
        public string doseSt { get; set; }
        public string doseHi { get; set; }
        public Nullable<int> index { get; set; }
        public Nullable<bool> show { get; set; }
        public Nullable<int> id_AntibioticGroup { get; set; }
        public string doseStandartPerOr { get; set; }
        public string doseStandart_Vv { get; set; }
        public string doseHighPerOr { get; set; }
        public string doseHigh_Vv { get; set; }
        public string note { get; set; }
        public string name { get; set; }
        public string abbr { get; set; }
        public Nullable<int> idTestGroup { get; set; }
        public Nullable<int> idConsumable { get; set; }
    
        public virtual a_AntibioticGroup a_AntibioticGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<d_Analyzes> d_Analyzes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<d_Analyzes> d_Analyzes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<d_Analyzes> d_Analyzes2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<d_Analyzes> d_Analyzes3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<d_Consumables> d_Consumables { get; set; }
        public virtual d_Consumables d_Consumables1 { get; set; }
        public virtual d_TestGroup d_TestGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<d_TestsPanel> d_TestsPanel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<g_ABDisk_ABTest_Interpritation> g_ABDisk_ABTest_Interpritation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<g_Microorganism_ABResSen> g_Microorganism_ABResSen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<g_Microorganism_TestsResults> g_Microorganism_TestsResults { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<p_Analises_Cultures_ABTest> p_Analises_Cultures_ABTest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<p_Analises_Mediums_Date_Colonies_Tests> p_Analises_Mediums_Date_Colonies_Tests { get; set; }
    }
}
