//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class g_ABDisk_ABTest_Interpritation
    {
        public int id { get; set; }
        public Nullable<int> idConsumable { get; set; }
        public Nullable<int> idTestAndAntibiotic { get; set; }
        public string rule { get; set; }
        public Nullable<int> idABMOGroup { get; set; }
    
        public virtual d_Consumables d_Consumables { get; set; }
        public virtual d_TestAndAntibiotic d_TestAndAntibiotic { get; set; }
        public virtual a_AntibioticMicroorganismGroup a_AntibioticMicroorganismGroup { get; set; }
    }
}
