//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class g_Equipment_DragMatal
    {
        public int id { get; set; }
        public int idEquipment { get; set; }
        public int idDragMetal { get; set; }
        public string quantity { get; set; }
    
        public virtual d_DragMetal d_DragMetal { get; set; }
        public virtual d_Equipment d_Equipment { get; set; }
    }
}
