//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class g_GroupMaterialPurpose_Accreditation
    {
        public int id { get; set; }
        public Nullable<int> idGMP { get; set; }
        public Nullable<int> idSubdivision { get; set; }
        public Nullable<bool> isAccreditation { get; set; }
    
        public virtual d_Subdivisions d_Subdivisions { get; set; }
        public virtual p_Group_Material_Purpose p_Group_Material_Purpose { get; set; }
    }
}
