//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class g_Institution_Email_Print
    {
        public int id { get; set; }
        public Nullable<int> idInstitution { get; set; }
        public Nullable<int> idDepartment { get; set; }
        public Nullable<int> index { get; set; }
        public Nullable<bool> show { get; set; }
        public Nullable<bool> isPrint { get; set; }
        public Nullable<bool> isSend { get; set; }
        public string name { get; set; }
        public string comment { get; set; }
    
        public virtual d_Department d_Department { get; set; }
        public virtual d_Institution d_Institution { get; set; }
    }
}
