//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class g_Medium_Consumables
    {
        public int id { get; set; }
        public Nullable<int> idMedium { get; set; }
        public Nullable<int> idConsumable { get; set; }
        public Nullable<double> quantity { get; set; }
    
        public virtual d_Consumables d_Consumables { get; set; }
        public virtual d_Medium d_Medium { get; set; }
    }
}
