//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class g_MicroorganismGroup_Microorganism
    {
        public int id { get; set; }
        public Nullable<int> idGroup { get; set; }
        public Nullable<int> idItem { get; set; }
        public Nullable<int> index { get; set; }
        public Nullable<bool> show { get; set; }
        public string additionalName { get; set; }
    
        public virtual d_Microorganism d_Microorganism { get; set; }
        public virtual d_MicroorganismGroup d_MicroorganismGroup { get; set; }
    }
}
