//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class g_Microorganism_TestsResults
    {
        public int id { get; set; }
        public Nullable<int> idMO { get; set; }
        public string res { get; set; }
        public Nullable<int> idTestPanel { get; set; }
        public Nullable<int> idTestAndAntibiotic { get; set; }
    
        public virtual d_Microorganism d_Microorganism { get; set; }
        public virtual d_TestAndAntibiotic d_TestAndAntibiotic { get; set; }
        public virtual d_TestsPanelName d_TestsPanelName { get; set; }
    }
}
