//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class l_log
    {
        public int id { get; set; }
        public int idStaff { get; set; }
        public int idAction { get; set; }
        public Nullable<int> labNum { get; set; }
        public string namePacient { get; set; }
        public Nullable<System.DateTime> dateDelivery { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public byte[] rezultOld { get; set; }
    
        public virtual d_Action d_Action { get; set; }
        public virtual d_Staff d_Staff { get; set; }
    }
}
