//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabPreparations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LabPreparations()
        {
            this.LabPreparationComponents = new HashSet<LabPreparationComponents>();
            this.LabSources = new HashSet<LabSources>();
        }
    
        public int ItemId { get; set; }
        public string Code { get; set; }
        public string Section { get; set; }
        public string Name { get; set; }
        public Nullable<int> Page { get; set; }
        public string pH { get; set; }
        public string Sterilization { get; set; }
        public string Storage { get; set; }
        public string ComponentsRaw { get; set; }
        public string Literature { get; set; }
        public string PreparationText { get; set; }
        public string SourceText { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LabPreparationComponents> LabPreparationComponents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LabSources> LabSources { get; set; }
    }
}
