//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabPreparationComponents
    {
        public int ComponentId { get; set; }
        public int ItemId { get; set; }
        public string Code { get; set; }
        public string Component { get; set; }
        public string Amount { get; set; }
        public string Unit { get; set; }
        public string Extraction { get; set; }
    
        public virtual LabPreparations LabPreparations { get; set; }
    }
}
