//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacLab
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BacLab_DBEntities : DbContext
    {
        public BacLab_DBEntities()
            : base("name=BacLab_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Analysis> Analyses { get; set; }
        public virtual DbSet<Britrany> Britranies { get; set; }
        public virtual DbSet<d_Antibiotics> d_Antibiotics { get; set; }
        public virtual DbSet<d_Antibiotics_groups> d_Antibiotics_groups { get; set; }
        public virtual DbSet<d_Category_of_patient> d_Category_of_patient { get; set; }
        public virtual DbSet<d_Department> d_Department { get; set; }
        public virtual DbSet<d_Diagnosis> d_Diagnosis { get; set; }
        public virtual DbSet<d_Diagnosis_group> d_Diagnosis_group { get; set; }
        public virtual DbSet<d_District> d_District { get; set; }
        public virtual DbSet<d_Finance> d_Finance { get; set; }
        public virtual DbSet<d_Gramm> d_Gramm { get; set; }
        public virtual DbSet<d_Group_of_Study> d_Group_of_Study { get; set; }
        public virtual DbSet<d_Institution> d_Institution { get; set; }
        public virtual DbSet<d_Material> d_Material { get; set; }
        public virtual DbSet<d_Medium> d_Medium { get; set; }
        public virtual DbSet<d_Microorganisms> d_Microorganisms { get; set; }
        public virtual DbSet<d_Microorganisms_genus> d_Microorganisms_genus { get; set; }
        public virtual DbSet<d_Microorganisms_groups> d_Microorganisms_groups { get; set; }
        public virtual DbSet<d_Morphology> d_Morphology { get; set; }
        public virtual DbSet<d_Name_Test_Set> d_Name_Test_Set { get; set; }
        public virtual DbSet<d_Olkenickiy> d_Olkenickiy { get; set; }
        public virtual DbSet<d_Purpose_of_study> d_Purpose_of_study { get; set; }
        public virtual DbSet<d_Staff_category> d_Staff_category { get; set; }
        public virtual DbSet<d_Test_result> d_Test_result { get; set; }
        public virtual DbSet<d_Tests> d_Tests { get; set; }
        public virtual DbSet<d_Type_Colonyy> d_Type_Colonyy { get; set; }
        public virtual DbSet<p_AB_MO_group_profile> p_AB_MO_group_profile { get; set; }
        public virtual DbSet<p_Group_Material> p_Group_Material { get; set; }
        public virtual DbSet<p_Group_Material_Purpose> p_Group_Material_Purpose { get; set; }
        public virtual DbSet<p_Group_Material_Purpose_Medium> p_Group_Material_Purpose_Medium { get; set; }
        public virtual DbSet<p_Identification_Table> p_Identification_Table { get; set; }
        public virtual DbSet<p_Institution_Department_District> p_Institution_Department_District { get; set; }
        public virtual DbSet<p_Purpose_CategoryPatient> p_Purpose_CategoryPatient { get; set; }
        public virtual DbSet<p_Test_Set> p_Test_Set { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Template_Results> Template_Results { get; set; }
    }
}
