//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_AB_MO_group_profile
    {
        public int id { get; set; }
        public int id_AB { get; set; }
        public int id_group_MO { get; set; }
        public int id_MO { get; set; }
        public int Res { get; set; }
        public int Sen { get; set; }
    
        public virtual d_Antibiotics d_Antibiotics { get; set; }
        public virtual d_Microorganisms d_Microorganisms { get; set; }
        public virtual d_Microorganisms_groups d_Microorganisms_groups { get; set; }
    }
}
