//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_Analises_Mediums
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public p_Analises_Mediums()
        {
            this.p_Analises_Mediums_Date = new HashSet<p_Analises_Mediums_Date>();
        }
    
        public int id { get; set; }
        public int idAnalis { get; set; }
        public int idMedium { get; set; }
        public Nullable<bool> isMain { get; set; }
        public Nullable<int> idMethodInoculation { get; set; }
        public string timeInoculation { get; set; }
        public string timeIncubation { get; set; }
        public string timeObservation { get; set; }
    
        public virtual d_MethodsInoculation d_MethodsInoculation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<p_Analises_Mediums_Date> p_Analises_Mediums_Date { get; set; }
        public virtual d_Medium d_Medium { get; set; }
        public virtual d_Analyzes d_Analyzes { get; set; }
    }
}
