//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_Analises_Mediums_Date_Colonies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public p_Analises_Mediums_Date_Colonies()
        {
            this.p_Analises_Mediums_Date_Colonies_AB = new HashSet<p_Analises_Mediums_Date_Colonies_AB>();
            this.p_Analises_Mediums_Date_Colonies_Serums = new HashSet<p_Analises_Mediums_Date_Colonies_Serums>();
            this.p_Analises_Mediums_Date_Colonies_Tests = new HashSet<p_Analises_Mediums_Date_Colonies_Tests>();
        }
    
        public int id { get; set; }
        public int idAnalisesMediumsDate { get; set; }
        public string quantity { get; set; }
        public Nullable<bool> oxidase { get; set; }
        public Nullable<bool> katalase { get; set; }
        public string comment { get; set; }
        public string hemolysis { get; set; }
        public Nullable<int> idMicroorganismGroup { get; set; }
        public Nullable<int> idMicroorganism { get; set; }
        public Nullable<int> idTargetPanelAB { get; set; }
        public Nullable<int> idSerotype { get; set; }
        public Nullable<int> idBiovariant { get; set; }
        public Nullable<bool> notTake { get; set; }
        public Nullable<int> idTargetPanelTests { get; set; }
        public string typeColony { get; set; }
        public string morphology { get; set; }
        public Nullable<int> idAnalisesCultures { get; set; }
    
        public virtual d_Biovariant d_Biovariant { get; set; }
        public virtual d_Microorganism d_Microorganism { get; set; }
        public virtual d_MicroorganismGroup d_MicroorganismGroup { get; set; }
        public virtual d_Serotype d_Serotype { get; set; }
        public virtual p_Analises_Cultures p_Analises_Cultures { get; set; }
        public virtual p_Analises_Mediums_Date p_Analises_Mediums_Date { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<p_Analises_Mediums_Date_Colonies_AB> p_Analises_Mediums_Date_Colonies_AB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<p_Analises_Mediums_Date_Colonies_Serums> p_Analises_Mediums_Date_Colonies_Serums { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<p_Analises_Mediums_Date_Colonies_Tests> p_Analises_Mediums_Date_Colonies_Tests { get; set; }
    }
}
