//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_Analises_Cultures_ABTest
    {
        public int id { get; set; }
        public Nullable<int> idAnalisesCulture { get; set; }
        public Nullable<int> idTestAndAntibiotic { get; set; }
        public string pm { get; set; }
        public Nullable<bool> ferment { get; set; }
        public Nullable<bool> fag { get; set; }
        public Nullable<bool> sinergizm { get; set; }
        public Nullable<bool> comment { get; set; }
        public Nullable<bool> onlyPerOr { get; set; }
        public Nullable<bool> onlyVV { get; set; }
        public Nullable<bool> abResSen { get; set; }
        public Nullable<int> index { get; set; }
        public Nullable<bool> ab { get; set; }
    
        public virtual d_TestAndAntibiotic d_TestAndAntibiotic { get; set; }
        public virtual p_Analises_Cultures p_Analises_Cultures { get; set; }
    }
}
