//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_Analises_Mediums_Date
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public p_Analises_Mediums_Date()
        {
            this.p_Analises_Mediums_Date_Colonies = new HashSet<p_Analises_Mediums_Date_Colonies>();
        }
    
        public int id { get; set; }
        public int idAnalisesMediums { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> idRezTemplateMedium { get; set; }
    
        public virtual d_RezTemplateMedium d_RezTemplateMedium { get; set; }
        public virtual p_Analises_Mediums p_Analises_Mediums { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<p_Analises_Mediums_Date_Colonies> p_Analises_Mediums_Date_Colonies { get; set; }
    }
}
