//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_Analises_Mediums_Date_Colonies_Tests
    {
        public int id { get; set; }
        public int idAnalisesMediumsDateColonies { get; set; }
        public string res { get; set; }
        public Nullable<int> index { get; set; }
        public Nullable<bool> show { get; set; }
        public string comment { get; set; }
        public Nullable<int> idTestAndAntibiotic { get; set; }
    
        public virtual d_TestAndAntibiotic d_TestAndAntibiotic { get; set; }
        public virtual p_Analises_Mediums_Date_Colonies p_Analises_Mediums_Date_Colonies { get; set; }
    }
}
