//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_Analises_DB
    {
        public int id { get; set; }
        public Nullable<int> idAnalysis { get; set; }
        public string bif { get; set; }
        public string lac { get; set; }
        public string ent { get; set; }
        public string coli1 { get; set; }
        public string coli2 { get; set; }
        public string coli3 { get; set; }
    
        public virtual d_Analyzes d_Analyzes { get; set; }
    }
}
