//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_Analises_Mediums_Date_Colonies_AB
    {
        public int id { get; set; }
        public int idAnalisesMediumsDateColonies { get; set; }
        public int idABMOGroup { get; set; }
        public string mm { get; set; }
        public string pm { get; set; }
        public string diapazonMM { get; set; }
        public Nullable<int> index { get; set; }
        public Nullable<bool> show { get; set; }
        public Nullable<bool> disk { get; set; }
        public Nullable<bool> ferment { get; set; }
        public Nullable<bool> fag { get; set; }
        public Nullable<bool> commentBurkholderia { get; set; }
        public string commentWhyEnabled { get; set; }
        public Nullable<bool> endFirstLine { get; set; }
        public string res { get; set; }
        public string sen { get; set; }
        public Nullable<int> idABSeries { get; set; }
        public string commentABControl { get; set; }
        public Nullable<bool> sinergizm { get; set; }
        public string specificity { get; set; }
        public string interpritation { get; set; }
        public Nullable<int> idConsumable { get; set; }
    
        public virtual d_Consumables d_Consumables { get; set; }
        public virtual p_Analises_Mediums_Date_Colonies p_Analises_Mediums_Date_Colonies { get; set; }
        public virtual d_ConsumablesStock d_ConsumablesStock { get; set; }
    }
}
