//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_Analises_Cultures_ABDisk
    {
        public int id { get; set; }
        public Nullable<int> idAnalisesCulture { get; set; }
        public Nullable<int> idConsumable { get; set; }
        public string mm { get; set; }
        public string pm { get; set; }
        public Nullable<int> index { get; set; }
        public Nullable<bool> forScrining { get; set; }
    
        public virtual d_Consumables d_Consumables { get; set; }
        public virtual p_Analises_Cultures p_Analises_Cultures { get; set; }
    }
}
