//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_Analises_Cultures
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public p_Analises_Cultures()
        {
            this.p_Analises_Cultures_ABDisk = new HashSet<p_Analises_Cultures_ABDisk>();
            this.p_Analises_Cultures_ABTest = new HashSet<p_Analises_Cultures_ABTest>();
            this.p_Analises_Mediums_Date_Colonies = new HashSet<p_Analises_Mediums_Date_Colonies>();
        }
    
        public int id { get; set; }
        public int idAnalises { get; set; }
        public int idCulture { get; set; }
        public Nullable<int> idSerotype { get; set; }
        public Nullable<int> idBiovariant { get; set; }
        public string quantity { get; set; }
        public Nullable<bool> hemolysis { get; set; }
        public Nullable<bool> proteolysis { get; set; }
        public Nullable<bool> lacPlusMinus { get; set; }
        public Nullable<bool> lacMinus { get; set; }
        public Nullable<bool> pat { get; set; }
        public Nullable<bool> betalactamase { get; set; }
        public Nullable<bool> blrs { get; set; }
        public Nullable<bool> carbopenemase { get; set; }
        public Nullable<bool> mrsa { get; set; }
        public Nullable<bool> pzb { get; set; }
        public Nullable<bool> vre { get; set; }
    
        public virtual d_Analyzes d_Analyzes { get; set; }
        public virtual d_Biovariant d_Biovariant { get; set; }
        public virtual d_Microorganism d_Microorganism { get; set; }
        public virtual d_Serotype d_Serotype { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<p_Analises_Cultures_ABDisk> p_Analises_Cultures_ABDisk { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<p_Analises_Cultures_ABTest> p_Analises_Cultures_ABTest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<p_Analises_Mediums_Date_Colonies> p_Analises_Mediums_Date_Colonies { get; set; }
    }
}
