//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_Group_Material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public p_Group_Material()
        {
            this.p_Group_Material_Purpose = new HashSet<p_Group_Material_Purpose>();
        }
    
        public int id { get; set; }
        public int id_group_of_study { get; set; }
        public int id_material { get; set; }
    
        public virtual d_Group_of_Study d_Group_of_Study { get; set; }
        public virtual d_Material d_Material { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<p_Group_Material_Purpose> p_Group_Material_Purpose { get; set; }
    }
}
