//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_Group_Material_Purpose_Medium
    {
        public int id { get; set; }
        public int id_GMP { get; set; }
        public Nullable<bool> is_main { get; set; }
        public Nullable<int> idMedium { get; set; }
        public Nullable<int> idMethodInoculation { get; set; }
        public string timeInoculation { get; set; }
        public string timeIncubation { get; set; }
        public Nullable<int> index { get; set; }
        public string timeObservation { get; set; }
    
        public virtual d_MethodsInoculation d_MethodsInoculation { get; set; }
        public virtual p_Group_Material_Purpose p_Group_Material_Purpose { get; set; }
        public virtual d_Medium d_Medium { get; set; }
    }
}
