//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_Group_Material_Purpose_Medium
    {
        public int id { get; set; }
        public int id_group_material_purpose { get; set; }
        public int id_Medium { get; set; }
    
        public virtual d_Medium d_Medium { get; set; }
        public virtual p_Group_Material_Purpose p_Group_Material_Purpose { get; set; }
    }
}
