//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_Group_Material_Purpose
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public p_Group_Material_Purpose()
        {
            this.d_Analyzes = new HashSet<d_Analyzes>();
            this.p_Group_Material_Purpose_Medium = new HashSet<p_Group_Material_Purpose_Medium>();
        }
    
        public int id { get; set; }
        public Nullable<bool> show { get; set; }
        public Nullable<int> idGroup { get; set; }
        public Nullable<int> idMaterial { get; set; }
        public Nullable<int> idPurpose { get; set; }
        public Nullable<int> index { get; set; }
        public Nullable<int> idReferenceInterval { get; set; }
        public Nullable<int> idPriceList { get; set; }
        public string abbr { get; set; }
        public Nullable<int> idTerraGMP { get; set; }
        public Nullable<bool> unit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<d_Analyzes> d_Analyzes { get; set; }
        public virtual d_GroupResearch d_GroupResearch { get; set; }
        public virtual d_Material d_Material { get; set; }
        public virtual d_PriceList d_PriceList { get; set; }
        public virtual d_Purpose d_Purpose { get; set; }
        public virtual d_ReferenceInterval d_ReferenceInterval { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<p_Group_Material_Purpose_Medium> p_Group_Material_Purpose_Medium { get; set; }
    }
}
