//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_Inner_Control
    {
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public int idRoom { get; set; }
        public Nullable<int> idEquipment { get; set; }
        public Nullable<int> idThermometer { get; set; }
        public Nullable<int> idStaff { get; set; }
        public Nullable<int> idDisinfectants { get; set; }
        public Nullable<bool> isEquipmentTemp { get; set; }
        public Nullable<bool> isEquipmentDisenf { get; set; }
        public Nullable<bool> isRoomTemp { get; set; }
        public Nullable<bool> isRoomDisenf { get; set; }
        public Nullable<bool> isLampTime { get; set; }
        public string comment { get; set; }
        public string timeCommon { get; set; }
        public Nullable<int> idEquipmentState { get; set; }
        public Nullable<bool> isRoomHumidity { get; set; }
        public string value { get; set; }
        public string currentMode { get; set; }
    
        public virtual d_Disinfectants d_Disinfectants { get; set; }
        public virtual d_Equipment d_Equipment { get; set; }
        public virtual d_Equipment d_Equipment1 { get; set; }
        public virtual d_EquipmentState d_EquipmentState { get; set; }
        public virtual d_Room d_Room { get; set; }
        public virtual d_Staff d_Staff { get; set; }
    }
}
