//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_Institution_Email
    {
        public int id { get; set; }
        public Nullable<int> idInstitution { get; set; }
        public string email { get; set; }
    
        public virtual d_Dictionary d_Dictionary { get; set; }
    }
}
