//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_Institution_Department_District
    {
        public int id { get; set; }
        public string name { get; set; }
        public string abbr { get; set; }
        public int id_institution { get; set; }
        public int id_department { get; set; }
        public int id_district { get; set; }
    
        public virtual d_Department d_Department { get; set; }
        public virtual d_District d_District { get; set; }
        public virtual d_Institution d_Institution { get; set; }
    }
}
