//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_Purpose_CategoryPatient
    {
        public int id { get; set; }
        public int id_purpose_of_study { get; set; }
        public int id_category_of_patient { get; set; }
    
        public virtual d_Category_of_patient d_Category_of_patient { get; set; }
        public virtual d_Purpose_of_study d_Purpose_of_study { get; set; }
    }
}
