//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class s_Document
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public s_Document()
        {
            this.s_Orders_Analyzes_Markers = new HashSet<s_Orders_Analyzes_Markers>();
            this.s_Orders_Analyzes_Markers1 = new HashSet<s_Orders_Analyzes_Markers>();
            this.s_Orders_Analyzes = new HashSet<s_Orders_Analyzes>();
            this.s_Orders = new HashSet<s_Orders>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string abbr { get; set; }
        public string abbr2 { get; set; }
        public string type { get; set; }
        public Nullable<int> index { get; set; }
        public Nullable<bool> show { get; set; }
        public byte[] file { get; set; }
        public byte[] tables { get; set; }
        public string status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<s_Orders_Analyzes_Markers> s_Orders_Analyzes_Markers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<s_Orders_Analyzes_Markers> s_Orders_Analyzes_Markers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<s_Orders_Analyzes> s_Orders_Analyzes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<s_Orders> s_Orders { get; set; }
    }
}
