//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class s_Orders_Analyzes_Markers
    {
        public int id { get; set; }
        public int idOrdersAnalyzes { get; set; }
        public int idMarker { get; set; }
        public string res { get; set; }
        public string norm { get; set; }
        public Nullable<int> idDocumentTest { get; set; }
        public Nullable<int> idDocumentNorm { get; set; }
        public Nullable<bool> isDivergence { get; set; }
        public string uncertainty { get; set; }
        public string сomment { get; set; }
        public Nullable<System.DateTime> dateEnd { get; set; }
        public Nullable<System.DateTime> timeEnd { get; set; }
    
        public virtual s_Document s_Document { get; set; }
        public virtual s_Document s_Document1 { get; set; }
        public virtual s_Markers s_Markers { get; set; }
        public virtual s_Orders_Analyzes s_Orders_Analyzes { get; set; }
    }
}
