//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class s_Orders_Analyzes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public s_Orders_Analyzes()
        {
            this.s_Orders_Analyzes_Markers = new HashSet<s_Orders_Analyzes_Markers>();
        }
    
        public int id { get; set; }
        public int idOrder { get; set; }
        public Nullable<System.DateTime> dateDelivery { get; set; }
        public Nullable<System.DateTime> timeDelivery { get; set; }
        public int idSubdivisions { get; set; }
        public Nullable<int> idStaff { get; set; }
        public Nullable<int> idDocumentTake { get; set; }
        public Nullable<int> idTara { get; set; }
        public Nullable<int> labNum { get; set; }
    
        public virtual d_Staff d_Staff { get; set; }
        public virtual d_Subdivisions d_Subdivisions { get; set; }
        public virtual s_Document s_Document { get; set; }
        public virtual s_Orders s_Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<s_Orders_Analyzes_Markers> s_Orders_Analyzes_Markers { get; set; }
        public virtual s_Tara s_Tara { get; set; }
    }
}
