//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class s_Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public s_Orders()
        {
            this.s_Orders_Analyzes = new HashSet<s_Orders_Analyzes>();
        }
    
        public int id { get; set; }
        public int num { get; set; }
        public Nullable<System.DateTime> dateSampling { get; set; }
        public Nullable<System.DateTime> timeSampling { get; set; }
        public int idSubdivisions { get; set; }
        public int idStaffRegistration { get; set; }
        public int idResearchGroup { get; set; }
        public Nullable<int> idPoint { get; set; }
        public Nullable<int> idCustomer { get; set; }
        public Nullable<int> idDocument { get; set; }
        public Nullable<int> idTransport { get; set; }
        public Nullable<int> idStorage { get; set; }
        public Nullable<int> idPreserve { get; set; }
        public string comment { get; set; }
        public string secondPerson { get; set; }
        public Nullable<int> idStaffValidation { get; set; }
        public Nullable<System.DateTime> dateEnd { get; set; }
        public Nullable<int> idFinance { get; set; }
    
        public virtual d_Institution d_Institution { get; set; }
        public virtual d_Staff d_Staff { get; set; }
        public virtual d_Staff d_Staff1 { get; set; }
        public virtual d_Subdivisions d_Subdivisions { get; set; }
        public virtual s_Document s_Document { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<s_Orders_Analyzes> s_Orders_Analyzes { get; set; }
        public virtual s_Point s_Point { get; set; }
        public virtual s_Preserve s_Preserve { get; set; }
        public virtual s_Storage s_Storage { get; set; }
        public virtual s_Transport s_Transport { get; set; }
    }
}
