//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int id { get; set; }
        public string lastName { get; set; }
        public string firstName { get; set; }
        public string middleName { get; set; }
        public int id_category { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string adress { get; set; }
        public string telephon1 { get; set; }
        public string telephon2 { get; set; }
        public string telephon3 { get; set; }
    
        public virtual d_Staff_category d_Staff_category { get; set; }
    }
}
